Neos:
  Flow:
    log:
      psr3:
        loggerFactory: 'Langeland\Monolog\LoggerFactory'
        'Langeland\Monolog\LoggerFactory':
          applicationLogger:
            defaultHandler:
              position: 100
              handler:
                className: 'Monolog\Handler\StreamHandler'
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/Application.log'
              processors:
                - 'Monolog\Processor\UidProcessor'

            jsonHandler:
              position: 100
              handler:
                className: 'Monolog\Handler\StreamHandler'
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/Application.json'
              formatter:
                className: 'Monolog\Formatter\LogstashFormatter'
                arguments:
                  0: 'Idun'
              processors:
                - 'Monolog\Processor\UidProcessor'

          systemLogger:
            defaultHandler:
              position: 100
              handler:
                className: 'Monolog\Handler\StreamHandler'
                arguments:
                  0: '%FLOW_PATH_DATA%Logs/System.json'
              formatter:
                className: 'Monolog\Formatter\LogstashFormatter'
                arguments:
                  0: 'Idun'
              processors:
                - 'Monolog\Processor\UidProcessor'